# Generated by Django 6.0.6 on 2026-06-09 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('accueil', 'Accueil'), ('choix_action', "Choix de l'action"), ('categorie_demandee', 'Catégorie demandée'), ('description_demandee', 'Description demandée'), ('recapitulatif', 'Récapitulatif'), ('suivi_ref_demandee', 'Référence de suivi demandée'), ('terminee', 'Terminée')], default='accueil', max_length=30)),
                ('contexte', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
