# Generated by Django 6.0.6 on 2026-06-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversation_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='etat',
            field=models.CharField(choices=[('accueil', 'Accueil'), ('choix_action', "Choix de l'action"), ('categorie_demandee', 'Catégorie demandée'), ('description_pour_suggestion', 'Description pour suggestion'), ('suggestion_proposee', 'Suggestion proposée'), ('description_demandee', 'Description demandée'), ('details_demandes', 'Précisions demandées'), ('recapitulatif', 'Récapitulatif'), ('suivi_ref_demandee', 'Référence de suivi demandée'), ('terminee', 'Terminée')], default='accueil', max_length=30),
        ),
    ]
