# Generated by Django 6.0.6 on 2026-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Référence lisible, ex. REC-2026-001 (générée en S2.4).', max_length=20, unique=True)),
                ('categorie', models.CharField(choices=[('notes', 'Notes'), ('scolarite', 'Scolarité'), ('examens', 'Examens'), ('bourse', 'Bourse')], max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', 'En cours'), ('attente_info', "En attente d'info"), ('resolue', 'Résolue'), ('cloturee', 'Clôturée')], default='soumise', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
