# Generated by Django 6.0.6 on 2026-06-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence lisible, ex. REC-2026-001 (générée automatiquement).', max_length=20, unique=True),
        ),
    ]
